version: '3'
services:
  bot:
    restart: always
    build: .
    env_file: ./.env
  db:
    image: "postgres:14.5"
    ports:
      - "5432:5435"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

